-- ============================================
-- BANK ACCOUNT MANAGEMENT SYSTEM
-- DATABASE TABLES
-- Oracle Database
-- ============================================

-- CUSTOMER TABLE
CREATE TABLE customer (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    phone VARCHAR2(15),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_customer
        PRIMARY KEY (customer_id),

    CONSTRAINT uk_customer_email
        UNIQUE (email)
);


-- ACCOUNT TABLE
CREATE TABLE account (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    account_number VARCHAR2(20) NOT NULL,
    customer_id NUMBER NOT NULL,
    account_type VARCHAR2(20) NOT NULL,
    balance NUMBER(15,2) DEFAULT 0 NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_account
        PRIMARY KEY (account_id),

    CONSTRAINT uk_account_number
        UNIQUE (account_number),

    CONSTRAINT fk_account_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(customer_id),

    CONSTRAINT chk_account_balance
        CHECK (balance >= 0),

    CONSTRAINT chk_account_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'CLOSED')),

    CONSTRAINT chk_account_type
        CHECK (account_type IN ('SAVINGS', 'CURRENT'))
);


-- BANK TRANSACTION TABLE
CREATE TABLE bank_transaction (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    transaction_reference VARCHAR2(50) NOT NULL,
    account_id NUMBER NOT NULL,
    transaction_type VARCHAR2(20) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR2(255),

    CONSTRAINT pk_bank_transaction
        PRIMARY KEY (transaction_id),

    CONSTRAINT uk_transaction_reference
        UNIQUE (transaction_reference),

    CONSTRAINT fk_transaction_account
        FOREIGN KEY (account_id)
        REFERENCES account(account_id),

    CONSTRAINT chk_transaction_amount
        CHECK (amount > 0),

    CONSTRAINT chk_transaction_type
        CHECK (
            transaction_type IN (
                'DEPOSIT',
                'WITHDRAWAL',
                'TRANSFER_IN',
                'TRANSFER_OUT'
            )
        )
);


-- AUDIT LOG TABLE
CREATE TABLE audit_log (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    account_id NUMBER,
    action_type VARCHAR2(50),
    old_balance NUMBER(15,2),
    new_balance NUMBER(15,2),
    action_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_audit_log
        PRIMARY KEY (audit_id)
);
